// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    throw UnsupportedError(
      'Android uses google-services.json per flavor (dev/prod). '
      'Use Firebase.initializeApp() without options on Android.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO9tSanARGVvlK_QeXAHgkHfWztXlVqI8',
    appId: '1:475949341237:web:b381c6abb774d74b262f7c',
    messagingSenderId: '475949341237',
    projectId: 'salikeencms',
    authDomain: 'salikeencms.firebaseapp.com',
    storageBucket: 'salikeencms.firebasestorage.app',
  );
}
