// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    throw UnsupportedError(
      'Android uses google-services.json per flavor (dev/prod). '
      'Use Firebase.initializeApp() without options on Android.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4zuqhlCTOj5w5IueW1Ua6Uw-U0OiRWwo',
    appId: '1:833070717357:web:8f92874d89f237f0aea924',
    messagingSenderId: '833070717357',
    projectId: 'salikeencms-prod',
    authDomain: 'salikeencms-prod.firebaseapp.com',
    storageBucket: 'salikeencms-prod.firebasestorage.app',
  );
}
